
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "defCONSTRAINT DECIMAL DEFINE DIRECT EQUAL HATE ID INTER_NODE INTRA_NODE LINKTYPE MATCH NUMBER PREFER SWITCH WAYPOINTempty :def : keyword ID '=' '(' defbody ')'\n    | keyword ID '=' '{' intrabody '}'\n    | keyword ID '=' '[' interbody ']'\n    | keyword ID '=' VALUE VALUE : NUMBER\n    keyword : LINKTYPE\n    | DEFINE\n    | INTRA_NODE\n    | INTER_NODEdefbody : NUMBER ',' NUMBERintrabody : intra intrabodytail\n    intrabodytail : empty\n    | ',' intra intrabodytailintra :  SWITCH CONSTRAINT '[' '(' tuple ')' WAYPOINT '(' ID ',' NUMBER ')' ']'\n    tuple : NUMBER tupletail\n    tupletail : empty\n    | ',' NUMBER tupletail\n    interbody : MATCH CONSTRAINT '(' tuple ')'\n    "
    
_lr_action_items = {'LINKTYPE':([0,],[3,]),'DEFINE':([0,],[4,]),'INTRA_NODE':([0,],[5,]),'INTER_NODE':([0,],[6,]),'$end':([1,12,13,21,23,28,],[0,-5,-6,-2,-3,-4,]),'ID':([2,3,4,5,6,47,],[7,-7,-8,-9,-10,48,]),'=':([7,],[8,]),'(':([8,29,32,45,],[9,33,35,47,]),'{':([8,],[10,]),'[':([8,27,],[11,32,]),'NUMBER':([8,9,22,33,35,42,49,],[13,15,30,37,37,44,50,]),'SWITCH':([10,26,],[18,18,]),'MATCH':([11,],[20,]),')':([14,30,36,37,38,40,41,44,46,50,],[21,-11,39,-1,43,-16,-17,-1,-18,51,]),',':([15,17,31,37,44,48,52,],[22,26,26,42,42,49,-15,]),'}':([16,17,24,25,31,34,52,],[23,-1,-12,-13,-1,-14,-15,]),'CONSTRAINT':([18,20,],[27,29,]),']':([19,39,51,],[28,-19,52,]),'WAYPOINT':([43,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'def':([0,],[1,]),'keyword':([0,],[2,]),'VALUE':([8,],[12,]),'defbody':([9,],[14,]),'intrabody':([10,],[16,]),'intra':([10,26,],[17,31,]),'interbody':([11,],[19,]),'intrabodytail':([17,31,],[24,34,]),'empty':([17,31,37,44,],[25,25,41,41,]),'tuple':([33,35,],[36,38,]),'tupletail':([37,44,],[40,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> def","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','dsl_yacc.py',13),
  ('def -> keyword ID = ( defbody )','def',6,'p_def','dsl_yacc.py',17),
  ('def -> keyword ID = { intrabody }','def',6,'p_def','dsl_yacc.py',18),
  ('def -> keyword ID = [ interbody ]','def',6,'p_def','dsl_yacc.py',19),
  ('def -> keyword ID = VALUE','def',4,'p_def','dsl_yacc.py',20),
  ('VALUE -> NUMBER','VALUE',1,'p_value','dsl_yacc.py',36),
  ('keyword -> LINKTYPE','keyword',1,'p_keyword','dsl_yacc.py',41),
  ('keyword -> DEFINE','keyword',1,'p_keyword','dsl_yacc.py',42),
  ('keyword -> INTRA_NODE','keyword',1,'p_keyword','dsl_yacc.py',43),
  ('keyword -> INTER_NODE','keyword',1,'p_keyword','dsl_yacc.py',44),
  ('defbody -> NUMBER , NUMBER','defbody',3,'p_defbody','dsl_yacc.py',48),
  ('intrabody -> intra intrabodytail','intrabody',2,'p_intrabody','dsl_yacc.py',53),
  ('intrabodytail -> empty','intrabodytail',1,'p_intra_body_tail','dsl_yacc.py',58),
  ('intrabodytail -> , intra intrabodytail','intrabodytail',3,'p_intra_body_tail','dsl_yacc.py',59),
  ('intra -> SWITCH CONSTRAINT [ ( tuple ) WAYPOINT ( ID , NUMBER ) ]','intra',13,'p_intra','dsl_yacc.py',65),
  ('tuple -> NUMBER tupletail','tuple',2,'p_tuple','dsl_yacc.py',74),
  ('tupletail -> empty','tupletail',1,'p_tupletail','dsl_yacc.py',79),
  ('tupletail -> , NUMBER tupletail','tupletail',3,'p_tupletail','dsl_yacc.py',80),
  ('interbody -> MATCH CONSTRAINT ( tuple )','interbody',5,'p_interbody','dsl_yacc.py',88),
]
